export const environment = {
  production: false,
  staging: true,
  uat: false,
  apiGraphQL: 'https://oxii-office-api.oxiitek.com/graphql',
  socketUri: 'https://oxii-office-api.oxiitek.com',
  apiWS: 'wss://oxii-office-api.oxiitek.com/graphql',
  // apiGraphQL: 'https://oxii-office-api.smarthiz.com/graphql',
  // socketUri: 'https://oxii-office-api.smarthiz.com',
  // apiWS: 'wss://oxii-office-api.smarthiz.com/graphql',
  firebaseConfig: {
    apiKey: "AIzaSyBvTklOwhZpokeEt5Q5U7tImUF94D1xsCI",
    authDomain: "soffice-stag.firebaseapp.com",
    projectId: "soffice-stag",
    storageBucket: "soffice-stag.appspot.com",
    messagingSenderId: "578605276145",
    appId: "1:578605276145:web:ed1cb80beb5efd6165c250",
  },
  vapidKey: "BFSKNtiG5n6V_j-S_PG4NeYu9XfQe1DEtvXxngD881MmcafvF-LscFV_349Q6ZABOcHkU4MtKKqlq-8famCpjY8",
  webChat: 'https://stg-office-web-chat.smarthiz.vn',
  googleApiKey: 'AIzaSyCokjDtTndRJtY-4tnXmGgC9ysIN-o1zv0',
  languagePrefix: 'so',
  languageBucket: 'https://test-languages.s3.ap-southeast-1.amazonaws.com',
  // staging: false,
  // uat: false,
  // apiGraphQL: 'https://oxii-office-api.oxiitek.com/graphql',
  // apiWS: 'wss://srt-steam-api.smarthiz.vn/graphql',
  // socketUri: 'https://oxii-office-api.oxiitek.com',
  // firebaseConfig: {
  //   apiKey: "AIzaSyBk52UadYLIe0TzIyQD1zqGNn8t0DhHmms",
  //   authDomain: "soffice-prod.firebaseapp.com",
  //   projectId: "soffice-prod",
  //   storageBucket: "soffice-prod.appspot.com",
  //   messagingSenderId: "50219916620",
  //   appId: "1:50219916620:web:2af253a5e3946b594003e9",
  // },
  // vapidKey: "BGaqz5ZBywBqvhykKVwtuoVsG5cyo6pUjGbeYdsAtWGM7NdKCANOK1KnbBEvIqupV44gS6xdwXkkeiY9eqTDl14",
  // languagePrefix: 'so',
  // languageBucket: 'https://test-languages.s3.ap-southeast-1.amazonaws.com',
  officeCmsUrl: 'http://192.168.2.98:4200/home/guest/approval?includeHeaderLayout=false'
};
